
package ma.service.ws.GetMessageActs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetMessageActsWS", targetNamespace = "http://***************")
public interface GetMessageActsWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<byte[]>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReadingActs", targetNamespace = "http://***************", className = "***************GetReadingActs")
    @ResponseWrapper(localName = "getReadingActsResponse", targetNamespace = "http://***************", className = "***************GetReadingActsResponse")
    public List<byte[]> getReadingActs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSendingAct", targetNamespace = "http://***************", className = "***************GetSendingAct")
    @ResponseWrapper(localName = "getSendingActResponse", targetNamespace = "http://***************", className = "***************GetSendingActResponse")
    public byte[] getSendingAct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

}
