
package ma.service.ws.GetUnreadMessages;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetUnreadMessagesWS", targetNamespace = "http://***************")
public interface GetUnreadMessagesWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnreadMessages", targetNamespace = "http://***************", className = "***************GetUnreadMessages")
    @ResponseWrapper(localName = "getUnreadMessagesResponse", targetNamespace = "http://***************", className = "***************GetUnreadMessagesResponse")
    public List<String> getUnreadMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
