
package ma.service.ws.GetUnreadMessages;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;

import ma.service.exploit.SafeEchangeExploitWs;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "getUnreadMessages", targetNamespace = "http://***************", wsdlLocation = "https://***************/getUnreadMessages?WSDL")
public class GetUnreadMessages_Service
    extends Service
{

    private final static URL GETUNREADMESSAGES_WSDL_LOCATION;
    private final static WebServiceException GETUNREADMESSAGES_EXCEPTION;
    private final static QName GETUNREADMESSAGES_QNAME = new QName("http://***************", "getUnreadMessages");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = SafeEchangeExploitWs.makeConnection("https://***************/getUnreadMessages?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETUNREADMESSAGES_WSDL_LOCATION = url;
        GETUNREADMESSAGES_EXCEPTION = e;
    }

    public GetUnreadMessages_Service() {
        super(__getWsdlLocation(), GETUNREADMESSAGES_QNAME);
    }

    public GetUnreadMessages_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns GetUnreadMessagesWS
     */
    @WebEndpoint(name = "GetUnreadMessagesWSImplPort")
    public GetUnreadMessagesWS getGetUnreadMessagesWSImplPort() {
        return super.getPort(new QName("http://***************", "GetUnreadMessagesWSImplPort"), GetUnreadMessagesWS.class);
    }

    private static URL __getWsdlLocation() {
        if (GETUNREADMESSAGES_EXCEPTION!= null) {
            throw GETUNREADMESSAGES_EXCEPTION;
        }
        return GETUNREADMESSAGES_WSDL_LOCATION;
    }

}
