
package ma.service.ws.SendMessage;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;

import ma.service.exploit.SafeEchangeExploitWs;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "sendMessageWS", targetNamespace = "http://***************", wsdlLocation = "https://***************/sendMessage?WSDL")
public class SendMessageWS_Service
    extends Service
{

    private final static URL SENDMESSAGEWS_WSDL_LOCATION;
    private final static WebServiceException SENDMESSAGEWS_EXCEPTION;
    private final static QName SENDMESSAGEWS_QNAME = new QName("http://***************", "sendMessageWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = SafeEchangeExploitWs.makeConnection("https://***************/sendMessage?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMESSAGEWS_WSDL_LOCATION = url;
        SENDMESSAGEWS_EXCEPTION = e;
    }

    public SendMessageWS_Service() {
        super(__getWsdlLocation(), SENDMESSAGEWS_QNAME);
    }

    public SendMessageWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SendMessageWS
     */
    @WebEndpoint(name = "SendMessageWSImplPort")
    public SendMessageWS getSendMessageWSImplPort() {
        return super.getPort(new QName("http://***************", "SendMessageWSImplPort"), SendMessageWS.class);
    }

    private static URL __getWsdlLocation() {
        if (SENDMESSAGEWS_EXCEPTION!= null) {
            throw SENDMESSAGEWS_EXCEPTION;
        }
        return SENDMESSAGEWS_WSDL_LOCATION;
    }

}
