
package ma.service.ws.ReadMessage;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;

import ma.service.exploit.SafeEchangeExploitWs;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "readMessage", targetNamespace = "http://***************", wsdlLocation = "https://***************/readMessage?WSDL")
public class ReadMessage_Service
    extends Service
{

    private final static URL READMESSAGE_WSDL_LOCATION;
    private final static WebServiceException READMESSAGE_EXCEPTION;
    private final static QName READMESSAGE_QNAME = new QName("http://***************", "readMessage");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = SafeEchangeExploitWs.makeConnection("https://***************/readMessage?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        READMESSAGE_WSDL_LOCATION = url;
        READMESSAGE_EXCEPTION = e;
    }

    public ReadMessage_Service() {
        super(__getWsdlLocation(), READMESSAGE_QNAME);
    }

    public ReadMessage_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReadMessageWS
     */
    @WebEndpoint(name = "ReadMessageWSImplPort")
    public ReadMessageWS getReadMessageWSImplPort() {
        return super.getPort(new QName("http://***************", "ReadMessageWSImplPort"), ReadMessageWS.class);
    }

    private static URL __getWsdlLocation() {
        if (READMESSAGE_EXCEPTION!= null) {
            throw READMESSAGE_EXCEPTION;
        }
        return READMESSAGE_WSDL_LOCATION;
    }

}
